In [1]:
import pickle
import pandas as pd
import numpy as np
from numpy.linalg import norm
from sklearn import preprocessing
import os

curpath = os.path.abspath(os.curdir)
rootpath = os.path.dirname(curpath)

In [2]:
#file_path = root_path + "/datasests/players.csv"

file_path = '/home/xzhang/zxw/good/code_5009/datasets/players.csv/player_mvp_stats.csv'
print(file_path)
import chardet
# read file
with open(file_path, 'rb') as f:
    data = f.read()
# use chardet to deduce the encoding of the file
result = chardet.detect(data)
encodingRes = result['encoding']
dataset = pd.read_csv(file_path, delimiter=';',encoding=encodingRes)
dataset.head()

/home/xzhang/zxw/good/code_5009/datasets/players.csv/player_mvp_stats.csv

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,0.477,...,0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,0.455,...,0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,0.340,...,0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,0.492,...,0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73

In [3]:
dataset.dtypes

Player      object
Pos         object
Age          int64
Tm          object
G            int64
GS           int64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won      int64
Pts Max      int64
Share      float64
Team        object
W            int64
L            int64
W/L%       float64
GB         float64
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [4]:
playerInfo = dataset['Player'] + dataset['Year'].astype(str)
# Year;Pts Won;Pts Max;Share;Team;W;L;W/L%;GB;PS/G;PA/G;SRS
items = dataset.drop(['Player','Year','Pos','Tm','GS','FGA','3PA','2PA','FTA','TRB','Share','Team','W','W/L%','L','GB','PS/G','PA/G','SRS'], 
        axis=1)
# print(type(items))
# items['Age'] = pd.to_numeric(items['Age'], errors='coerce')
# items['Age'] = items['Age'].fillna(0).astype(int)

In [5]:
x = items.values
min_max_scaler = preprocessing.MinMaxScaler()

In [6]:
print(x)
print(len(x))

[[27.  82.  26.4 ...  9.1  0.   0. ]
 [29.  82.  32.1 ... 14.5  0.   0. ]
 [22.  52.   7.3 ...  2.8  0.   0. ]
 ...
 [25.  54.  23.5 ... 10.8  0.   0. ]
 [19.  57.   9.9 ...  4.   0.   0. ]
 [25.  80.  29.2 ...  8.5  0.   0. ]]
14092

In [7]:
import numpy as np



# Iterate over each row in x
for i in range(len(x)):
    row = x[i]
    # Check if the first element of the row is 'Age'
    if row[0] == 'Age':
        # Delete the row
        x = np.delete(x, i, axis=0)

In [8]:
x = np.delete(x, 47, axis=0)
print(x[47])

[24.    33.     5.9    0.9    0.357  0.       nan  0.9    0.357  0.357
  0.4    0.591  0.6    1.1    0.2    0.1    0.2    0.3    0.9    2.2
  0.     0.   ]

In [9]:

x_scaled = min_max_scaler.fit_transform(x)

In [10]:
'''
Age -- Player's age on February 1 of the season
Tm -- Team
Lg -- League
Pos -- Position
G -- Games
GS -- Games Started
MP -- Minutes Played Per Game
FG -- Field Goals Per Game
FGA -- Field Goal Attempts Per Game
FG% -- Field Goal Percentage
3P -- 3-Point Field Goals Per Game
3PA -- 3-Point Field Goal Attempts Per Game
3P% -- 3-Point Field Goal Percentage
2P -- 2-Point Field Goals Per Game
2PA -- 2-Point Field Goal Attempts Per Game
2P% -- 2-Point Field Goal Percentage
eFG% -- Effective Field Goal Percentage
This statistic adjusts for the fact that a 3-point field goal is worth one more point than a 2-point field goal.
FT -- Free Throws Per Game
FTA -- Free Throw Attempts Per Game
FT% -- Free Throw Percentage
ORB -- Offensive Rebounds Per Game
DRB -- Defensive Rebounds Per Game
TRB -- Total Rebounds Per Game
AST -- Assists Per Game
STL -- Steals Per Game
BLK -- Blocks Per Game
TOV -- Turnovers Per Game
PF -- Personal Fouls Per Game
PTS -- Points Per Game
'''

playerInfo = dataset['Player'] + dataset['Year'].astype(str)
items = dataset.drop(['Player','Year','Pos','Tm','GS','FGA','3PA','2PA','FTA','TRB','Team'], 
        axis=1)

x = items.values
min_max_scaler = preprocessing.MinMaxScaler()
# x = [[int(num) for num in range(len(x[row]))] for row in range(len(x))]
x_scaled = min_max_scaler.fit_transform(x)
x_scaled = x_scaled / norm(x_scaled, axis=1)[:, None]
items = pd.DataFrame(x_scaled, columns=items.columns)

In [11]:
playerInfo

0            A.C. Green1991
1           Byron Scott1991
2        Elden Campbell1991
3         Irving Thomas1991
4          James Worthy1991
                ...
14087     Spencer Hawes2017
14088       Steve Novak2017
14089    Terrence Jones2017
14090        Thon Maker2017
14091        Tony Snell2017
Length: 14092, dtype: object

In [12]:
items

,Age,G,MP,FG,FG%,3P,3P%,2P,2P%,eFG%,...,Pts Won,Pts Max,Share,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0.145459,0.405208,0.253860,0.102572,0.200023,0.007929,0.084043,0.104186,0.213049,0.136150,...,0.0,0.0,0.0,0.324712,0.100051,0.322129,0.037519,0.268410,0.143618,0.339759
1,0.167156,0.380985,0.290219,0.189770,0.188460,0.067092,0.128011,0.169793,0.204264,0.134332,...,0.0,0.0,0.0,0.305301,0.094070,0.302873,0.035276,0.252364,0.135032,0.319448
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.154066,0.333809,0.321656,0.263797,0.179164,0.020613,0.105241,0.264840,0.183898,0.121628,...,0.0,0.0,0.0,0.281392,0.086704,0.279154,0.032514,0.232602,0.124458,0.294432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,0.191233,0.313713,0.168390,0.097875,0.240647,0.046906,0.153636,0.082183,0.276446,0.175348,...,0.0,0.0,0.0,0.263669,0.244656,0.257481,0.079908,0.282444,0.213987,0.267191
14088,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14089,0.133314,0.312426,0.266279,0.167655,0.232728,0.037371,0.125277,0.159599,0.251544,0.161424,...,0.0,0.0,0.0,0.262588,0.243653,0.256425,0.079580,0.281285,0.213109,0.266096
14090,0.020758,0.359798,0.122266,0.063744,0.247721,0.050915,0.204006,0.044603,0.277404,0.192852,...,0.0,0.0,0.0,0.286203,0.265565,0.279486,0.086737,0.306582,0.232275,0.290026
14091,0.121031,0.422784,0.300380,0.109731,0.204542,0.152675,0.182514,0.048298,0.246349,0.176220,...,0.0,0.0,0.0,0.238393,0.221203,0.232799,0.072248,0.255368,0.193474,0.241578

In [13]:
items.dtypes

Age        float64
G          float64
MP         float64
FG         float64
FG%        float64
3P         float64
3P%        float64
2P         float64
2P%        float64
eFG%       float64
FT         float64
FT%        float64
ORB        float64
DRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Pts Won    float64
Pts Max    float64
Share      float64
W          float64
L          float64
W/L%       float64
GB         float64
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [14]:
curpath = os.path.abspath(os.curdir)
rootpath = os.path.dirname(curpath)
print(rootpath)

/home/xzhang/zxw/good/code_5009

In [18]:
import os

wb_path = '/home/xzhang/zxw/good/code_5009/datasets/'
with open(os.path.expanduser(wb_path+'nba_players.pkl'), 'wb') as fout:
    pickle.dump([items,playerInfo], fout)